services:
  # Backend (Laravel)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hms-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
    depends_on:
      - db

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hms-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  # Database
  db:
    image: postgres:15
    container_name: hms-db
    restart: always
    environment:
      POSTGRES_DB: hospital_management
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  # Backend (Flask)
  flask_app:
    build: ./ml
    container_name: hms-flask-api
    ports:
      - "5001:5001"
    volumes:
      - ./ml:/app
    environment:
      - FLASK_ENV=development

  pgadmin:
    image: dpage/pgadmin4
    container_name: hms-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db